name: stockappflutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  intl: ^0.20.2
  http: ^1.3.0
  auto_size_text: ^ 3.0.0
  firebase_database: ^11.3.5
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true